%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

#imu_topic: "/mavros/imu/data_raw"
#imu_topic: "/camera/imu"
imu_topic: "/imu0"
image0_topic: "/cam0/image_raw"
image1_topic: "/cam1/image_raw"
#image0_topic: "/camera/infra1/image_rect_raw"
#image1_topic: "/camera/infra2/image_rect_raw"
output_path: "/home/xu/vins_output/"

cam0_calib: "left1.yaml"
cam1_calib: "right1.yaml"
image_width: 1280
image_height: 720
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.01301095634388352, -0.005070623738001712,
       0.9999024971415602, 0.03671615355111148,
       -0.9999097972900367, 0.003267771869320563,
       0.01302762259241452, 0.02169026717979497,
       -0.003333511424589375, -0.9999818050554322,
       -0.005027649516865795, -0.0000578135929000942, 0., 0., 0., 1. ]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.01129080808837021, -0.004471320310557636,
       0.9999262597548844, 0.03767186874423049,
       -0.9999301632412926,   0.00344058703135805,
       0.01130623726631103, -0.0980688527108189,
       -0.003490887129951881,-0.9999840847011319,
       -0.004432161040157589, -0.0002632245838794373, 0., 0., 0., 1. ]
#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.5  # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.3  # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.002   # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 0.002   # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805         # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.017                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/vins_output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
